---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "delly_filter"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::delly=1.2.6"
